is2/urls.py
from django.contrib import admin
from django.urls import path
from is2.views import inicio, saludo, documentaciones, step1_CrearRol, step2_CrearRol, step1_SprintPlanning, \
    step1_asignarRol, \
    step2_asignarRol, crearProyecto, \
    registrarUsuario, \
    modificarProyecto, verMiembros, step1_modificarRol, step2_modificarRol, step3_modificarRol, \
    crearHistoria, sprintBacklog, \
    seleccionarHistoria, modificarHistoria, eliminarProyecto, eliminarHistoria, modificarSprint, visualizarSprint, \
    tableroKanban, moverHistoria, visualizarSprint2, lineChart, asignarHistoriaEncargado, asignarSprint, productBacklog, \
    swichProyecto, importarRol, step1_eliminarRol, step2_eliminarRol, \
    search, swichProyecto, importarRol, step1_eliminarRol, step2_eliminarRol, step2_SprintPlanning, \
    asignarCapacidad, step3_SprintPlanning, step3_asignarEncargado, tableroQA_Release, eliminarSprint, moverHistoriaQA, \
    visualizarSprintFilter, historicoSprint, HistorialProyectoFilter, HistorialSprintFilter, \
    HistorialProductBacklog, BurndownChart, finalizarProyecto, iniciarProyecto, finalizarOexpandirSprint, infoProyecto, \
    infoUsuario, modificarProyecto2, tableroQA_Release2, modificarHistoria2, eliminarHistoria2, step1_SprintPlanning2, \
    step2_SprintPlanning2, asignarCapacidad2, step3_SprintPlanning2, step3_Funcionalidades, modificarSprint2, \
    sprintBacklog2, tableroKanban2, moverHistoria2, funcionalidadesQA, KanbanHistorico, eliminarSprint2, homeProyecto, \
    eliminarProyecto2, intercambiarMiembro, accesoDenegado, infoSprint, informe_US_ProductBacklog, informe_Sprint, \
    informe_Historia_Sprint,informe_BurndownChart, historicoProyecto, informe_Proyecto
from django.conf.urls import url


#Librerias importadas del autenticador
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.urls import include, re_path


urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('bienvenida/',saludo), # hola mundo para probar si funciona el sistema
    path('documentacion/',documentaciones), #Todavia no implementado, para mostrar las documentaciones en la pagina
    path('AccesoDenegado/',accesoDenegado),

    #URL relacionados a roles y usuario
    path('crearRol/1/',step1_CrearRol), #ok
    path('crearRol/2/',step2_CrearRol), #ok
    path('modificarRol/1/', step1_modificarRol), #ok
    path('modificarRol/2/', step2_modificarRol), #ok
    path('modificarRol/3/', step3_modificarRol), #ok
    path('asignarRol/1/', step1_asignarRol), #ok
    path('asignarRol/2/', step2_asignarRol), #ok
    path('eliminarRol/1/',step1_eliminarRol), #ok
    path('eliminarRol/2/',step2_eliminarRol), #ok
    path('registrarUsuario/',registrarUsuario), #ok
    path('Usuario/<int:id_usuario>/info/',infoUsuario),

    #URL relacionado a proyecto
    path('proyecto/nuevo/',crearProyecto), #ok only superuser
    #path('proyecto/',HistorialProyectoFilter),
    path('proyecto/<int:id_proyecto>/',homeProyecto),#
    path('proyecto/<int:id_proyecto>/Sprints/', HistorialSprintFilter),
    path('proyecto/<int:id_proyecto>/ProductBacklog/', HistorialProductBacklog),
    path('proyecto/<int:id_proyecto>/Finalizar/', finalizarProyecto), #ok
    path('proyecto/<int:id_proyecto>/iniciar/', iniciarProyecto), #ok
    path('proyecto/<int:id_proyecto>/modificar/', modificarProyecto2),
    path('proyecto/<int:id_proyecto>/Resumen/',infoProyecto),
    path('proyecto/<int:id_proyecto>/eliminar/',eliminarProyecto2), #ok
    path('importarRoles/',importarRol),
    path('inicio/<int:id>/',swichProyecto),
    path('proyecto/<int:id_proyecto>/historial/',historicoProyecto),
    path('proyecto/<int:id_proyecto>/informeRegistro/',informe_Proyecto),
    #NUEVOS URLS relacionados a Historia

    path('proyecto/<int:id_proyecto>/ProductBacklog/nuevo/', crearHistoria),
    path('proyecto/<int:id_proyecto>/ProductBacklog/modificar/Historia<int:id_historia>/', modificarHistoria2),
    path('proyecto/<int:id_proyecto>/ProductBacklog/Eliminar/Historia<int:id_historia>/', eliminarHistoria2),


    #NUEVOS URLS  relacionados al Manejo de Sprint.
         #estos paths son de crear nuevo sprint
    path('proyecto/<int:id_proyecto>/Sprints/nuevo/InformacionBasica/', step1_SprintPlanning2),
        #esto no se usa
    path('proyecto/<int:id_proyecto>/Sprints/nuevo/FormarEquipo/', step2_SprintPlanning),
    path('proyecto/<int:id_proyecto>/Sprints/nuevo/AsignarHistorias/', step3_SprintPlanning),
    path('proyecto/<int:id_proyecto>/Sprints/nuevo/FormarEquipo/<int:id_usuario>', asignarCapacidad),
    #ojo
    #path('proyecto/<int:id_proyecto>/Sprints/nuevo/AsignarEncargado/<int:id>/<int:opcion>/', step3_asignarEncargado),

        #estos paths son de modificar.
    path('proyecto/<int:id_proyecto>/Sprints/modificar/<int:id_sprint>/InformacionBasica/',modificarSprint2),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/FormarEquipo/', step2_SprintPlanning2),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/AsignarHistorias/', step3_SprintPlanning2),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/FormarEquipo/<int:id_usuario>/<str:opcion>', asignarCapacidad2),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/AsignarEncargado/Historia<int:id_historia>/Op<int:opcion>/', step3_Funcionalidades),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/Eliminar/', eliminarSprint2), #ok
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/info/', infoSprint), #ok


    #URL relacionados a los aspectos relacionados al sprint
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/SprintBacklog/',sprintBacklog2),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/KanbanActivo/',tableroKanban2), # FalTa
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/KanbanActivo/Historia<int:id_historia>/Op<int:opcion>', moverHistoria2), #Falta
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/BurndownChart/',BurndownChart),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/KanbanActivo/accion+<str:opcion>/',finalizarOexpandirSprint),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/intercambiar/',intercambiarMiembro),


    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/QualityAssurance/',tableroQA_Release2),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/QualityAssurance/<int:id_historia>/<int:opcion>/', funcionalidadesQA),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/kanbanHistorico/',KanbanHistorico),
    path('proyecto/<int:id_proyecto>/exportUS/', informe_US_ProductBacklog),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/exportUS/', informe_Sprint),
    path('proyecto/<int:id_proyecto>/exportUSALL/', informe_Historia_Sprint),
    path('proyecto/<int:id_proyecto>/Sprints/<int:id_sprint>/exportBurndownChart/',informe_BurndownChart),

    #----------------------------------OLD URLS------------------------------------------


    #Url ya desactualizado
    path('tableroKanban/<int:id_sprint>/<str:opcion>/', finalizarOexpandirSprint),
    path('tableroKanban/', tableroKanban),
    path('tableroKanban/<int:id>/<int:opcion>/', moverHistoria),
    #URL RELACIONADAS A SPRINT
    path('SprintPlanning/1/', step1_SprintPlanning),
    #path('proyecto/<int:id_proyecto>/Sprints/nuevo/InformacionBasica/', step1_SprintPlanning),

    path('SprintPlanning/2/', step2_SprintPlanning),
    #path('proyecto/<int:id_proyecto>/Sprints/nuevo/FormarEquipo/', step2_SprintPlanning),
    path('SprintPlanning/2/<int:id>/', asignarCapacidad),
    #path('proyecto/<int:id_proyecto>/Sprints/nuevo/FormarEquipo/<int:id_usuario>', asignarCapacidad),

    path('SprintPlanning/3/', step3_SprintPlanning),
    #path('proyecto/<int:id_proyecto>/Sprints/nuevo/AsignarHistoria/', step3_SprintPlanning),

    path('SprintPlanning/3/<int:id>/<int:opcion>/', step3_asignarEncargado),
    #path('proyecto/<int:id_proyecto>/Sprints/nuevo/AsignarHistoria/<int:id_historia>/<int:opcion>/', step3_asignarEncargado),

    path('sprintBacklog/<int:id_sprint>/',sprintBacklog),
    #path('sprint/<int:id_sprint>/BackLog/',sprintBacklog),

    path('modificarSprint/<int:id_sprint>/',modificarSprint),
    #path('sprint/<int:id_sprint>/modificar/',modificarSprint),
    path('eliminarSprint/<int:id_sprint>/',eliminarSprint),

    #ya no se usa
    path('visualizarSprint/',visualizarSprint),
    #ya no se usa
    path('visualizarSprint/<int:id>/',visualizarSprint2),
    #path('KanBan/Historico/<int:id>/',visualizarSprint2),

    #URL relacionada a historias
    path('modificarHistoria/1/', seleccionarHistoria),
    path('modificarHistoria/2/', modificarHistoria),
    path('eliminarHistoria/', eliminarHistoria),


    # no se usa mas
    path('modificarProyecto/', modificarProyecto),
    path('eliminarProyecto/', eliminarProyecto),

    path('verHistorias/',productBacklog),
    path('verHistorias/<int:id>/',asignarSprint),
    path('asignarEncargado/',asignarHistoriaEncargado),
    #path('tableroKanban/<str:opcion>/',tableroKanban),



    path('listarMiembros/',verMiembros),
    #path('burndownChart/',lineChart),

    path('burndownChart/<int:id_sprint>/',BurndownChart),
    #path('sprint/<int:id_sprint>/BurndownChart/',BurndownChart),

    #path('historicooSprint/<int:id_sprint>/',historicoSprint2),
    #path('sprint/<int:id>/KanBan/Historico/',historicoSprint2),

    #URL relacionado a la tablero QA
    path('qualityassurance/<int:id_sprint>/',tableroQA_Release2),
    #path('sprint/<int:id_sprint>/QualityAssurance/',tableroQA_Release2),
    path('qaRelease/<int:id>/<int:id_sprint>/<int:opcion>/', moverHistoriaQA),
    #path('sprint/<int:id_sprint>/QuealityAssurance/<int:opcion>/<int:id>/', moverHistoriaQA),

    #viejo ya no se usan
    path('qaRelease/<int:id>/', tableroQA_Release),
    path('qaRelease/', tableroQA_Release),

Sprints/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

# Create your models here.
from userStory.models import Historia

"""
Definimos los posibles estados del Sprint
"""
ESTADOS_CHOICES=[
    ('PLANNING','Planning'),
    ('INICIADO','Iniciado'),
    ('FINALIZADO','Finalizado'),
]

class Sprint(models.Model):
    """
    Clase de Sprint, almacena datos generales acerca de los sprint de un proyecto:
    identificador, Numero de Sprint, fecha de inicio, fecha fin, historias, estados, verificado, horas laborales real e ideal
    """

    id = models.AutoField(primary_key=True)
    sprintNumber = models.IntegerField()
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    fecha_final= models.DateField(null=True)
    historias = models.ManyToManyField(Historia,blank=True)
    estados = models.CharField(max_length=20, choices=ESTADOS_CHOICES,default='PLANNING')
    #El Sprint es verificado, cuando el Scrum realiza todos los QA de las historias y confirma
    verificado = models.BooleanField(default=False)

    ##Esto lo agrege yo por que estoy re loco
    horasLaboralesReal = ArrayField(models.IntegerField(), default=list, blank=True)
    horasLaboralesIdeal = ArrayField(models.IntegerField(), default=list, blank=True)

    def validate_test(self):
        """
        Metodo del modelo de Sprint que retorna un booleano en caso
        que se hayan completado o no todos los campos obligatorios en el sprint.
        """

        if not self.sprintNumber:
            return False
        if not self.fecha_inicio:
            return False
        if not self.fecha_fin:
            return False
        return True

templates/IntercambiarMiembro.html
{% include 'material/includes/material_css.html' %}
{% load material_form %}

{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
      $(document).ready(function(){
        $('select').formSelect();
      });
    </script>
    <meta charset="UTF-8">
    <title>Importar ROles</title>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

<body>

    <div class="container">
        <div class="card-action">
            <a href="http://127.0.0.1:8000/inicio/" style="color:dodgerblue;">
                <i class="material-icons" style="vertical-align: -5px;">home</i>Volver a Inicio
            </a>
        </div>
        <h3> Intercambiar desarrolladores</h3>
        <div class="row">
            {% if form.errors %}
                <script>M.toast({html: "Por favor revisa los campos", classes: 'red rounded', displayLength:5000});</script>
            {% endif %}

            <form action="" method="POST">
                {% csrf_token %}
                {% form form=form %}{% endform %}

                <input type="submit" value="Siguente" class="btn red">
            </form>
        </div>

    </div>

</body>
</html>

templates/SprintBacklog.html
{% load socialaccount %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <!-- Compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Sprint Backlog</title>
</head>
<body>


 <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #2f2f2f;">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button
                    class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Navbar brand -->
                <a class="navbar-brand mt-2 mt-lg-0" href="#">
                    <img src="https://image.flaticon.com/icons/png/512/3486/3486614.png" height="15" alt=""
                         loading="lazy"
                         style="width:50px;height:50px;">
                    Grupo 8
                </a>

                <!-- Left links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/inicio/">Inicio</a></li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/proyecto/{{ ID_proyecto }}/Sprints">Volver al Sprint</a></li>



                    {% if perms.Sprints.add_sprint and proyecto.estado == "INICIADO" %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                               href="/proyecto/{{ ID_proyecto }}/Sprints/nuevo/InformacionBasica/">Crear Sprint</a>
                        </li>
                    {% endif %}
                </ul>

            </div>
            <!-- Collapsible wrapper -->

            <!-- Right elements -->
            <div class="container_row " >
                <div class="layer1 d-flex justify-content-end" style="color: white">
                    {{ usuario.first_name }} {{ usuario.last_name }}
                </div>
                <div class="layer2 d-flex justify-content-end" style="color: white">
                    {{ usuario.email }}
                </div>
                <div class="layer3 d-flex justify-content-end" style="color: white">
                     {{ proyecto.nombre }} | {{ Rol_de_usuario }}
                </div>

            </div>

            <div class="d-flex align-items-center">

                <div class="nav-item dropstart">
                    <a type="button" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"
                       aria-expanded="false">

                        {% if user.is_superuser %}
                            <img src="/static/estilos/img/admin-with-cogwheels.png" alt="" class="rounded-circle"
                                 style='filter: invert(100%);width:50px;height:50px;'>
                        {% else %}
                            <img src="{{ avatar }}" alt="" class="rounded-circle" style="width:50px;height:50px;">
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu">
                        {% if not user.is_superuser %}
                            <li><a class="dropdown-item" href="/Usuario/{{ usuario.pk }}/info/">Ver Informacion</a></li>

                        {% endif %}
                        <li><a class="dropdown-item" href="/inicio/logout">Cerrar Sesion</a></li>
                    </ul>
                </div>


            </div>
        </div>
    </nav>

<p></p>
<div class="container">
  <div class="row">
    <h3 class="text-info">SPRINT BACKLOG</h3>
      <h4>Sprint Numero : {{ sprint.sprintNumber }}</h4>
      <h5>Cantidad de Historias : {{ cantidad_de_historias }}</h5>
  </div>
    {% if not historiasAlta and not historiasBaja and not historiasMedia %}
    <div class="card-action" style="position:relative; left:10px;">
        <p><i class="material-icons red-text" style="vertical-align: -5px;">info</i> Aun no hay historias creadas</p>
    </div>
{% else %}
    <a class="btn btn-primary btn-lg" href="/proyecto/{{ ID_proyecto }}/Sprints/{{ sprint.id }}/exportUS/" target="_blank" role="button"><i class="fas fa-file-pdf">&nbsp;Imprimir</i></a>
    <p></p>
{% endif %}
</div>

<div class="container">
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Prioridad</th>
      <th scope="col">Fecha Creacion</th>
      <th scope="col">Encargado</th>
      <th scope="col">Horas Estimadas</th>
      <th scope="col">Horas Dedicadas</th>
      <th scope="col">Estado</th>
    </tr>
  </thead>
  <tbody>
          {% for historia in historiasAlta %}
    <tr>
        <th scope="row">{{ historia.id_historia }}</th>
        <td>{{ historia.nombre }}</td>
        <td>{{ historia.descripcion }}</td>
        <td>{{ historia.prioridad }}</td>
        <td>{{ historia.fecha_creacion }}</td>
        {% if historia.encargado %}
            <td>{{ historia.encargado }}</td>
        {% else %}
            <td>---</td>
        {% endif %}

        <td>{{ historia.horasEstimadas }}</td>
        <td>{{ historia.horas_dedicadas }}</td>
        {% if historia.estados %}
        <td>{{ historia.estados }}</td>
        {% else %}
         <td></td>
        {% endif %}
    </tr>
          {% endfor %}
  </tbody>

<tbody>
          {% for historia in historiasMedia %}
    <tr>
        <th scope="row">{{ historia.id_historia }}</th>
        <td>{{ historia.nombre }}</td>
        <td>{{ historia.descripcion }}</td>
        <td>{{ historia.prioridad }}</td>
        <td>{{ historia.fecha_creacion }}</td>
        {% if historia.encargado %}
            <td>{{ historia.encargado }}</td>
        {% else %}
            <td>---</td>
        {% endif %}

        <td>{{ historia.horasEstimadas }}</td>
        <td>{{ historia.horas_dedicadas }}</td>
        {% if historia.estados %}
        <td>{{ historia.estados }}</td>
        {% else %}
         <td></td>
        {% endif %}
    </tr>
          {% endfor %}
  </tbody>

<tbody>
          {% for historia in historiasBaja %}
    <tr>
        <th scope="row">{{ historia.id_historia }}</th>
        <td>{{ historia.nombre }}</td>
        <td>{{ historia.descripcion }}</td>
        <td>{{ historia.prioridad }}</td>
        <td>{{ historia.fecha_creacion }}</td>
        {% if historia.encargado %}
            <td>{{ historia.encargado }}</td>
        {% else %}
            <td>---</td>
        {% endif %}

        <td>{{ historia.horasEstimadas }}</td>
        <td>{{ historia.horas_dedicadas }}</td>
        {% if historia.estados %}
        <td>{{ historia.estados }}</td>
        {% else %}
         <td></td>
        {% endif %}
    </tr>
          {% endfor %}
  </tbody>
</table>
</div>

</body>
</html>

templates/index_old.html
{% load socialaccount %}
{% load static %}
<!DOCTYPE html>
<html lang="es">

<!-- nombre de la pestanha e informaciones de la pagina -->


<head>
    <title>Proyecto IS2</title>
    <meta charset="utf-8"/>
    <!-- Debe mostrarse en la version de edge -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!--bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>

    <!-- importar el estilo a la pagina web-->
    <link rel="stylesheet" href="{% static '/estilos/style.css' %}"/>



</head>

<!-- Aqui va el codigo de la pagina -->

<body>
<header>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://image.flaticon.com/icons/png/512/3486/3486614.png" style="width:30px;height:30px;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/inicio/">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/docs/">Documentaciones</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="logout">salir</a>
                    </li>
                </ul>
                <span class="navbar-text">
                        Bienvenido al sistema de gestion de Proyectos agiles con tablero kanban del grupo 8
                    </span>
            </div>
        </div>
    </nav>
    <div class="cover d-flex flex-column justify-content-center align-items-center">
        <h1>
            Proyecto Scrum
        </h1>

        <p>
            Gestion de proyectos agiles
        </p>
        {% if user.is_authenticated and user %}
            <p style="color:darkgrey;">Bienvenido al sistema<p>
        {% else %}
            <a href="{% provider_login_url 'google' %}">
                <button type="button" class="btn btn-secondary">
            Iniciar sesion
        </button>
            </a>
        {% endif %}
    </div>
</header>

</body>

</html>

templates/outputAsignarRol.html
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}

{% load static %}

<!DOCTYPE html>
<html lang="es">

<!-- nombre de la pestanha e informaciones de la pagina -->


<head>

    <title>Rol asignado</title>
    <meta charset="utf-8"/>
    <!-- Debe mostrarse en la version de edge -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

</head>


<body>

  <div class="row">
    <div class="col s12 m6">
      <div class="card light-blue darken-3">
        <div class="card-content white-text">
          <span class="card-title">Asignacion de rol exitosa!</span>
            <p>Usuario: {{ asignaciondeRol.Usuario }}
            <br>Rol: {{ asignaciondeRol.Roles }}
            </p>
        </div>
        <div class="card-action">
          <a href="javascript:history.back()" style="color:#bcdbe3;">Asignar otro Rol</a>
          <a href="http://127.0.0.1:8000/inicio/" style="color:#bcdbe3;">Inicio</a>
        </div>
      </div>
    </div>
  </div>

</body>

</html>

templates/outputEliminarRol.html
{% include 'material/includes/material_css.html' %}
{% include 'material/includes/material_js.html' %}

{% load static %}

<!DOCTYPE html>
<html lang="es">

<!-- nombre de la pestanha e informaciones de la pagina -->


<head>

    <title>Rol Eliminado</title>
    <meta charset="utf-8"/>
    <!-- Debe mostrarse en la version de edge -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

</head>


<body>

  <div class="row">
    <div class="col s12 m6">
      <div class="card light-blue darken-3">
        <div class="card-content white-text">
          <span class="card-title">Eliminacion de rol exitosa!</span>
            <p>Rol : {{ roleliminado}}

            </p>
        </div>
        <div class="card-action">
          <a href="javascript:history.back()" style="color:#bcdbe3;">eliminar otro Rol</a>
          <a href="http://127.0.0.1:8000/inicio/" style="color:#bcdbe3;">Inicio</a>
        </div>
      </div>
    </div>
  </div>

</body>

</html>